### ISSUE TITLE
multiple labels in an environment

### ISSUE THREAD

**Issue by davidfarmer** [jthomasbarry/aafmt#15]
Near line 426 of algcodes.tex there is a \label{noteHammingdist}.  That is the second
label in that definition, and there should only be one label per environment.

The noteHammingdist label is not actually used anywhere, so it should be deleted.

There are more than a dozen places where similar things occur.  In all cases I saw,
the extraneous label is in the middle of the environment.  It is best to put the label,
if there is one, at the very beginning of the environment.

**Comment by christhron** [comment]
This is legacy code, and is not necessary. I've deleted all that I can find.
