### ISSUE TITLE
Wording at end of chapter 9

### ISSUE THREAD

**Issue by davidfarmer** [jthomasbarry/aafmt#16]
The start of this sentence:

Until now, apparently no physicist or mathematician has offered a satisfactory explanation for Wigner's "miracle"

Gives the impression that you mean to go on and say:  "But now someone has!"

Rephrasing, such as "No physicist or mathematician has ever offered...." would be less confusing.

**Comment by davidfarmer** [comment]
Also at the beginning of that section is the phrase:

 what we\'ve accomplished so far.

delete the backslash in front of the apostrophe.

**Comment by christhron** [comment]
Thanks, I will change the wording.
