### ISSUE TITLE
Hard space in Latex code

### ISSUE THREAD

**Issue by christhron** [jthomasbarry/aafmt#20]
I understand that ~ doesn't work in MathJax, but I would think it should work in a non-math environment.  (see the table after Proposition 3.2.1 in Section 3.2)

**Comment by davidfarmer** [comment]
This is sort-of fixed.

The way the source makes things line up is not really the right way to do it,
but I am not sure the conversion to html would work if the source was more complicated.
So, leave it alone for now.

**Comment by christhron** [comment]
Looks fine. I'm happy with it
