### ISSUE TITLE
Reference to section doesn't work

### ISSUE THREAD

**Issue by christhron** [jthomasbarry/aafmt#21]
At the beginning of Section 6.3, there is a \ref to Section 4.4.7 which doesn't work.  How will \ref's to sections be handled?

**Comment by davidfarmer** [comment]
Refs to sections should now be hyperlinks to the appropriate section.

**Comment by davidfarmer** [comment]
Link in item a in Section 5.2.1 is still broken.

**Comment by davidfarmer** [comment]
These seem to be working now.  Those links were tricky, so I can't be sure that all cases are
handled correctly.  Please look around a bit before closing this issue.

**Comment by christhron** [comment]
seems fine
