### ISSUE TITLE
bfii and term

### ISSUE THREAD

**Issue by davidfarmer** [jthomasbarry/aafmt#25]
I propose the macro \term{...}, which is short for \terminology{...}, when one introduces new terminology.

It is possible that all uses of bfii are the same as what I mean by term.  If so, then you can
leave those alone for now.

But I would like to see different macros.  Please define \term and \terminology as
\newcommand{\terminology}[1]{\textbf{\textit{{#1}}}}
\newcommand{\term}{\terminology}

and eventually plan to phase out \bfii.

**Comment by davidfarmer** [comment]
And if you get a chance, please explain to me why there is usually a space at the start of
the argument of bfii.  Maybe that is just inherited from other sources?

**Comment by christhron** [comment]
Hi David,
I've looked at \bfii.  It's perfectly OK with me (and very simple)  to
change our master file so that it defines \term, and do a global replace of
\bfii with \term in all .tex files.  Let me know if you want me to do this.

As you expected, the space at the beginning of the argument  of \bfii is a
legacy artifact.  I can also use TextCrawler to eliminate all of these
spaces.  let me know if you want me to do this.

**Comment by davidfarmer** [comment]
I think it would be good to convert all the bfii to term, if indeed
they all serve the same purpose.  No hurry, but if you can easily
do it while also taking care of other things, then please do.
Deleting the extraneous space would also be good.  But note that
not all instances of bfii have the extra space.

The reason I raised this issue is that I am thinking about the index,
and it is natural to automatically include all defined terms in the
index.  Presumably the author(s) have made an appropriate index
entry, but there is more information in "term" because it says
"here is the official definition", while "index" merely says
"people may want to look here for information about this word".

**Comment by christhron** [comment]
I will make the \bfii change.  It's very easy.

So if you define \term to automatically generate an index entry, what
happens if the index entry is already specified?  Will I have to go through
and remove existing index entries?

  Also, what happens in cases like \term{Abelian group} where you might
want the index entry to be \index{Group!Abelian}  ?

**Comment by davidfarmer** [comment]
A good index always has the same entry in multiple places.
\index{Group!Abelian} says that "Group" is a heading in the
index, and "Abelian" is under it.  It is in a completely
different place (alphabetically) than the "Abelian group" entry.
But both of those should be in the index.
It is common to have 2 or 3 index entries grouped together
in the LaTeX source.

The slightly hard part (for me, not the author) is when you
have  \term{rigid motion}\index{Rigid motion}.  That is an
actual example from the text (once bfii is changed to term).
Or even slightly more difficult: when one is plural and the
other is not.

Based on my brief scan of some of the index entries, it looks
like there should be a lot more entries.  But luckily, once
things are working, the \term{...} items which currently don't
seem to have a corresponding \index{...}, will now be okay
because \term{...} will automatically generate an index entry
in the html.

Perhaps consider changing the LaTeX definition to
\newcommand{\terminology}[1]{\textbf{\textit{{#1}}}\index{#1}}

Or maybe not, since you seem to prefer capitalized index
entries, but it is rare to have capitalized words inside term.

**Comment by christhron** [comment]
Hi David,

If you don't mind, I'm not going to add the \index just yet. It is possible
to change uppercase index references to lowercase using regular
expressions, but I'd prefer to do it when I have a graduate student who can
take care of the details. Jordan is now working on his thesis, so he
doesn't have time to worry about this.

I will be making a commit soon with \bfii replaced with \term

Thanks
chris

**Comment by davidfarmer** [comment]
That it fine and you can close this issue.
I'll work on the html index, and work on the pdf index can be left for 
later.

**Comment by christhron** [comment]
bfii's are gone
