### ISSUE TITLE
No spacing between tables

### ISSUE THREAD

**Issue by christhron** [jthomasbarry/aafmt#28]
In 11.2.15 the tables all merge together, even though there is a \bigskip between two of the tables.

This may be an issue with \multicols

**Comment by davidfarmer** [comment]
It looks like consecutive list items have no vertical space between them.
Somehow that never mattered before.  It is easy for me to globally
add space between adjacent list items, but I need to check a bit to make
sure that doesn't mess up something else.

**Comment by davidfarmer** [comment]
Fixed

**Comment by christhron** [comment]
good
