### ISSUE TITLE
\enumi doesn't work

### ISSUE THREAD

**Issue by christhron** [jthomasbarry/aafmt#29]
In Section  7.4 just before 7.4.15, there's an example with items (a), (b), (c), (d).  But they display as (a), (b), (a), (b).  It seems this is because \enumi{2} isn't working.  Can this be fixed?

**Comment by davidfarmer** [comment]
It can be fixed by adding (c) and (d) directly, which is okay because you hard code the reference
instead of using \label and \ref.

Fix coming in a pull request shortly.

**Comment by christhron** [comment]
No longer an issue
