### ISSUE TITLE
terminology arguments

### ISSUE THREAD

**Issue by davidfarmer** [jthomasbarry/aafmt#35]
I suggest modifying these uses of terminology as described:
In cosets.tex
 \term{Euler} $\phi$-\term{function}
to
 \term{Euler $\phi$-function}

In functions.tex, change this line
We say that $g$ is an \term{inverse} of~$f$ if and only if:
so that the \term{} argument is \term{inverse function}.
(The issue is that "inverse" means something different in most of the book.)

**Comment by davidfarmer** [comment]
And in Chapter 4, in the paragraph before the definition of "group", put 'group' in \emph{...}
instead of \term{...}, because the \term{...} is in the definition which immediately follows.

**Comment by davidfarmer** [comment]
Same in set_chapter.tex in the first paragraph of
Do the subsets of a set form a group?

The \term{group} should only be used once: in the place where "group" is officially defined.

Maybe we could use \term*{group) in those other places?  The appearance would be the
same, but the star means that this is not the official definition.  Let me know what you think
and I'll implement whatever we decide.

**Comment by christhron** [comment]
I made all changes suggested.  I don't think it's necessary to define \term*. You shouldn't define a lot of non-standard Latex commands.  I just replaced with \textbf{textit{}

**Comment by davidfarmer** [comment]
If we already have \term then \term\* seems pretty simple and
intuitive.  I'll make a pull request with that if I can get it
working.

Almost anything is better than directly calling \textit and
\textbf.  Those should not appear in the document source,
only in the macro definitions.
