### ISSUE TITLE
terms which should not be linked

### ISSUE THREAD

**Issue by davidfarmer** [jthomasbarry/aafmt#39]
This is a followup  to issue #35 .

If you use \textbf{\textit{...}} for the "term"s which should not be automatically
linked, then you need to make sure that all of the old  \textbf{\textit{...}}s have been
converted to \term{...}, and that you tell me this has been done.

The problem is that the conversion script automatically converts \textbf{\textit{...}} to term,
because formerly it had to do that.  If that conversion is no longer necessary, then
I'll take that away from the script.

**Comment by christhron** [comment]
Hi David,

Are you free? Can we talk on the phone or Skype?  We have several issues.

**Comment by christhron** [comment]
This issue is closed.  the genuine "term"s have been made into "term".
