### ISSUE TITLE
Hints work for chapters 1-7, but not for Chapter 8

### ISSUE THREAD

**Issue by christhron** [jthomasbarry/aafmt#42]
I like the way you changed the hint references.  Do I need to change the Latex code for Chapter 8?

**Comment by davidfarmer** [comment]
I'm not sure I understand what is different.  Can you point to
a couple specific examples?

It has been a while since I change anything about the hints.

**Comment by christhron** [comment]
For example, the hints in exercise 8.1.7.  I checked my pdf, and they work
fine there.

**Comment by christhron** [comment]
It appears to work now
