### ISSUE TITLE
proper way to show brackets

### ISSUE THREAD

**Issue by davidfarmer** [jthomasbarry/aafmt#5]
To show a literal curly bracket "{" or "}", you can use a { in math mode.
Other methods that work in LaTeX, but not in HTML.

For example, the lines
Let $\var{Men}$ = {men in the country}, and
$\var{Women}$ = {women in the country}.
in functions.tex
do not produce the correct output, because the { is not in math mode.

It is necessary to systematically convert these and all the other non-math mode literal
brackets into math mode.

**Comment by jthomasbarry** [comment]
I have fixed the examples here but I will look for more. I will not close this issue yet.

**Comment by christhron** [comment]
it's been long enough
