### ISSUE TITLE
Please do another update

### ISSUE THREAD

**Issue by christhron** [jthomasbarry/aafmt#50]
Hi David,

My student and I finally figured out GitHub.  From here on out it should be smooth sailing.

Can you please do another update? We've added a chapter.

thanks

**Comment by davidfarmer** [comment]
Done, but please check for obvious errors.

**Comment by christhron** [comment]
Your online compile is different from my pdf. my pdf doesn't have polynomial codes, and it also has the hints. So I'm not sure what's wrong.  Are you using aafmt.tex to compile?
You can see my pdf at:  http://abstractalgebra.altervista.org/aafmt.pdf

**Comment by christhron** [comment]
Resolved
