### ISSUE TITLE
Induction section

### ISSUE THREAD

**Issue by davidfarmer** [jthomasbarry/aafmt#63]
In Base case, (*) should be (P(n))
http://sl2x.aimath.org/book/aafmt/section19-1.html

In several places, the list markers are hard-coded as (a), (b), etc,
but the list actually uses numbers.
In one place, \underline{~~...~} needs to go outside of \text{}
"Chapter 1" is hard-coded.
\slshape should be deleted.
(*) and (**) need to be changed
http://sl2x.aimath.org/book/aafmt/section19-3.html

(*) should be (P(n)) in several places:
http://sl2x.aimath.org/book/aafmt/section19-10.html

**Comment by christhron** [comment]
All changes made
